<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99010a1068656c6c6f776f726c642e70726f746f120968656c6c6f2e61707022180a0752657175657374120d0a057175657279180120012809221a0a08526573706f6e7365120e0a066f757470757418012001280932370a0548656c6c6f122e0a0373617912122e68656c6c6f2e6170702e526571756573741a132e68656c6c6f2e6170702e526573706f6e73654203d00201620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

