<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace Hello\App;

/**
 * Protobuf type <code>hello.app.Hello</code>
 */
interface HelloInterface
{
    /**
     * Method <code>say</code>
     *
     * @param \Hello\App\Request $request
     * @return \Hello\App\Response
     */
    public function say(\Hello\App\Request $request);

}

